spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: password
      database: getir
      port: 27017
      host: localhost

getir-security:
  username: getir
  password: password
  secret: fqKqe2WKiCOJNMMoRmB9/TqqK2GHUbmA94VHJ3yijMgHISWYBi5lZDv+iIGByGOAfdl351tmSg1v3RyasaulxQ==